site_name: xnrl
site_url: https://U-S-NRL-Marine-Meteorology-Division.github.io/xnrl
repo_url: https://github.com/U-S-NRL-Marine-Meteorology-Division/xnrl
edit_uri: /edit/main/docs/
markdown_extensions:
    - admonition
    - attr_list
    - codehilite
    - md_in_html
    - meta
    - pymdownx.highlight:
        use_pygments: true
    - pymdownx.superfences
    - pymdownx.tabbed
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_root_heading: True
            show_object_full_path: False
            show_category_heading: False
            show_bases: False
            show_signature: False
            heading_level: 1
      watch:
        - xnrl/
        - README.md

nav:
    - Home: index.md
    - Main: main.md
    - Util: util.md