name: Publish to PyPI

on:
  push:
    #On any tag
    tags:
      - "*"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    name: Build
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: |
        python -m pip install --upgrade pip
        python setup.py sdist
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_TOKEN }}
    # - name: Publish package to TestPyPI
    #   uses: pypa/gh-action-pypi-publish@release/v1
    #   with:
    #     verbose: true
    #     password: ${{ secrets.TEST_PYPI_TOKEN }}
    #     repository_url: https://test.pypi.org/legacy/             