name: Publish to PyPi

on:
  push:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    name: Build
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - run: python setup.py build